### ISSUE TITLE
[MacOS] Build Failed

### ISSUE THREAD

**Issue by railnation** [GradleFx/GradleFx#248]
Hi, 

I have to use our Mac for building the Application and I get the following error:

Failed to apply plugin [id 'gradlefx'] any hints?

Regards

**Comment by RIAstar** [comment]
You don't give us much to work with.
Could you provide a bit more information ?

Versions of Gradle, GradleFx; stacktrace; etc.

**Comment by railnation** [comment]
Gradle version: 3.4.1, GradleFx: 1.5.0 

`The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at org.gradle.api.internal.AbstractTask.leftShift(AbstractTask.java:513)
        at org.gradle.api.Task$leftShift.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at build_2lra4sj2l28ar7kz02o3cjhn0.run(/Users/csobolewski/Perforce/csobolewski_next_version_mac/build.gradle:35)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:599)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:233)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:230)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:160)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Create bundle for stream

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/csobolewski/Perforce/csobolewski_next_version_mac/04_script/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating project ':04_script'.
> Failed to apply plugin [id 'gradlefx']
   > Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':04_script'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:599)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:233)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:230)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:160)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'gradlefx']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:44)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_f3rxplphdcu3vl2vlb5ckkfcu.run(/Users/csobolewski/Perforce/csobolewski_next_version_mac/04_script/build.gradle:10)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 62 more
Caused by: org.gradle.api.InvalidUserDataException: Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.
        at org.gradle.language.base.plugins.LifecycleBasePlugin$6.execute(LifecycleBasePlugin.java:128)
        at org.gradle.language.base.plugins.LifecycleBasePlugin$6.execute(LifecycleBasePlugin.java:124)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:203)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:197)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:94)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:93)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:111)
        at org.gradle.api.tasks.TaskContainer$create.call(Unknown Source)
        at org.gradlefx.plugins.AbstractGradleFxPlugin.addTask(AbstractGradleFxPlugin.groovy:75)
        at org.gradlefx.plugins.GradleFxPlugin.addTasks(GradleFxPlugin.groovy:47)
        at org.gradlefx.plugins.AbstractGradleFxPlugin.apply(AbstractGradleFxPlugin.groovy:48)
        at org.gradlefx.plugins.AbstractGradleFxPlugin.apply(AbstractGradleFxPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
        ... 72 more`

**Comment by SlevinBE** [comment]
That's strange, the build task of GradleFx was renamed to buildFx specifically to avoid this error. So it shouldn't happend anymore in 1.5.0.
Can you share your build.sbt file (or parts thereof which are not confidential)?

**Comment by railnation** [comment]
What exactly do you mean by build.sbt. Is that a macOS specific file? (I am a Mac Noob) :dagger: 
Sorry for my late response I dont get a notification.

**Comment by SlevinBE** [comment]
sorry, that should've been 'build.gradle'. I'm mixing up build system files, built.sbt is used for the SBT build tool (similar to Gradle, but used mainly in Scala development)

**Comment by railnation** [comment]
Hope this buid file helps:

import org.apache.tools.ant.taskdefs.condition.Os

buildscript {
	repositories {
		mavenLocal()
		mavenCentral()
	}
	dependencies {
		classpath group: 'org.gradlefx', name: 'gradlefx', version: '1.5.0'
	}
}

apply plugin: 'gradlefx'
import groovy.xml.XmlUtil
import groovy.util.XmlParser

jvmArguments = ['-Xmx1024m','-Xms512m']

dependencies {
	if (project.mobileTarget == "and")
	{
		internal files(....)
	}
	else if (project.mobileTarget == "ios")
	{
		internal files("...")
	}
}

flexHome = project.airHomePath

version = '1.0-SNAPSHOT'
type = 'mobile'
srcDirs = ["../../01_dev/src/"]
//resourceDirs = ['$rootDir/02_deploy/01_game']
 
air {
	if (project.mobileTarget == "and")
	{
		additionalCompilerOptions = [
		  "-target-player=25.0",
		  "-swf-version=36",
		  "-default-size=1920,1080",
		  "-define+=CONFIG::release, true",
		  "-define+=CONFIG::debug, false",  
		  "-define+=CONFIG::mobile, true",
		  "-define+=CONFIG::google, true",
		  "-define+=CONFIG::apple, false",
		  "-define+=CONFIG::editor, false",
		  "-define+=CONFIG::desktop, false",
		  "-define+=CONFIG::adl, false",
		  "-define+=CONFIG::desktopApp, false",
		  "-conservative=true",
		  "-omit-trace-statements=true",
		  "-optimize=true"
		]
	
		includeFileTrees = [
			fileTree(dir: "$rootDir/", includes: [
				'11_icons/android/icons/icon_36.png',
				'11_icons/android/icons/icon_48.png',
				'11_icons/android/icons/icon_72.png',
				'11_icons/android/icons/icon_96.png',
				'11_icons/android/icons/icon_144.png',
				'11_icons/android/icons/icon_192.png',
				'assets/adapters.info'
			])
		]
		
		applicationDescriptor = "$rootDir/02_deploy/application_google.xml"
		keystore 			  = "$rootDir/05_cert/*********************.p12"
		storepass			  =	'**************************'
	}
	else if (project.mobileTarget == "ios")
	{
		additionalCompilerOptions = [
		  "-target-player=25.0",
		  "-swf-version=36",
		  "-default-size=1920,1080",
		  "-define+=CONFIG::release, true",
		  "-define+=CONFIG::debug, false",  
		  "-define+=CONFIG::mobile, true",
		  "-define+=CONFIG::google, false",
		  "-define+=CONFIG::apple, true",
		  "-define+=CONFIG::editor, false",
		  "-define+=CONFIG::desktop, false",
		  "-define+=CONFIG::adl, false",
		  "-define+=CONFIG::desktopApp, false",
		  "-omit-trace-statements=true",
		  "-conservative=true",
		  "-optimize=true"
		]
		
		includeFileTrees = [
			fileTree(dir: "../../", includes: [
				'11_icons/ios/icons/icon_29.png',
				'11_icons/ios/icons/icon_40.png',
				'11_icons/ios/icons/icon_48.png',
				'11_icons/ios/icons/icon_50.png',
				'11_icons/ios/icons/icon_57.png',
				'11_icons/ios/icons/icon_58.png',
				'11_icons/ios/icons/icon_60.png',
				'11_icons/ios/icons/icon_72.png',
				'11_icons/ios/icons/icon_76.png',
				'11_icons/ios/icons/icon_80.png',
				'11_icons/ios/icons/icon_87.png',
				'11_icons/ios/icons/icon_100.png',
				'11_icons/ios/icons/icon_114.png',
				'11_icons/ios/icons/icon_120.png',
				'11_icons/ios/icons/icon_144.png',
				'11_icons/ios/icons/icon_152.png',
				'11_icons/ios/icons/icon_167.png',
				'11_icons/ios/icons/icon_180.png',
				'11_icons/ios/icons/icon_512.png',
				'11_icons/ios/icons/icon_1024.png',
				'15_fb/ios/GoogleService-Info.plist'
			])
		]
		
		fileOptions = ['-C', "build/resources/", '.']
		
		// live version
		if (project.iosLive == "true")
		{
			applicationDescriptor = "../../02_deploy/application_ios.xml"
			keystore 			  = "../../05_cert/********************.p12"
			storepass			  =	'******************************'
		}
		else 
		{
			// test version
			applicationDescriptor = "../../02_deploy/application_ios_dev.xml"
			keystore 			  = "../../05_cert/*************.p12"
			storepass			  =	'******************************************'
		}
		
		println applicationDescriptor + " || " + keystore + " || " + storepass
		
	}
}


airMobile {
	platform = project.mobileTarget
	
	if (platform == "ios")
	{
		output = 'RailnationApple'
	 	outputExtension = 'ipa'
	 	mainClass = 'com/traviangames/railnation/MainApple.as'
	 	if (project.iosLive == "true")
	 	{
	 		// live version
	 		provisioningProfile = "../../05_cert/Rail_Nation_World_Store.mobileprovision"
	 		target = 'ipa-app-store'
	 	}
	 	else 
	 	{
	 		// test version
	 		provisioningProfile = "../../05_cert/Rail_Nation_World_Dev.mobileprovision"
	 		target = 'ipa-debug'
	 	}
	} 
	else if (platform == "and")
	{
		output = 'RailnationGoogle'
		outputExtension = 'apk'
		mainClass = 'com/traviangames/railnation/MainGoogle.as'
		target = 'apk-captive-runtime'
	}
}

task copyFiles(type:Copy,dependsOn: ["copyDefaultsIOS"]){
	if (project.mobileTarget == "ios")
	{
		from ( "$rootDir/02_deploy/01_game" ) {
			exclude 'assetsExported/android-etc', 'assetsExported/desktop-dxt', 'videos', 'desktopbuild', 'fonts'
		}
		into "$deployDirMob"
	} 
	else if (project.mobileTarget == "steam")
	{
		from ( "$rootDir/02_deploy/01_game" ) {
			exclude 'assetsExported/android-etc', 'assetsExported/ios-pvrtc', 'desktopbuild'
		}
		into "$deployDirMob"
	}
}

task copyDefaultsIOS(type:Copy){
	if (project.mobileTarget == "ios")
	{
		from ( "$rootDir/11_icons/ios" ) {
			exclude 'icons'
		}
		into "$deployDirRoot"
	}
}

task copyToDistribution(type: Copy,dependsOn: ["copyFiles","packageMobile"]) {
	from (buildDir)
	into "$apkDir"
}

task clean << {
	delete ("$rootDir/04_script/mobile/build/resources/01_game")
	delete ("$rootDir/04_script/mobile/build")
} 

task deployOnDevice(type:Exec, dependsOn:["copyToDistribution"]){	
	if (Os.isFamily(Os.FAMILY_WINDOWS)) 
	{
		commandLine "cmd", "/c", "$rootDir/copyToDevice.bat", project.mobileTarget, "notRoot", project.appVersion, project.packageName, project.airHomePath
	}
}

**Comment by railnation** [comment]
Mhm any news on this?

**Comment by SlevinBE** [comment]
This is still a mystery to me. The stacktrace references a piece of code which was there in GradleFx versions before 1.4.0, but your buildscript defines version 1.5.0.
I've tried the same setup on my local machine, so Gradle version 3.4.1 and GradleFx version 1.5.0, and it's working fine. When I go back to GradleFx 1.3.0 I get the same error as you do (as expected).

Can you try removing the "mavenLocal()" statement in the beginning of your build script, so that it can't fetch it from your local repo? Maybe there's a corrupt 1.5.0 version in your local maven repo.

**Comment by railnation** [comment]
removing mavenLocal() does not work. same error occurs.

**Comment by railnation** [comment]
How could I update my local repo?

**Comment by railnation** [comment]
Done. Fixed all issues in my build scripts
